import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

function Home({posts}) {
  const {data} = posts;
  // console.log('posts', posts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data && data.map((item, index) => {
          return (
            <div  key={index}>
              <p>email: {item.email}</p>
              <p>name: {item.last_name} {item.first_name}</p>
              <div className={styles.image}>
                <Image layout="fill" objectFit="cover" src={item.avatar} alt={item.first_name}/>
              </div>
              <Link href={`/posts/${item.id}`}>進入</Link>
            </div>
          )
        })}
      </main>
    </>
  )
}

// export async function getStaticPaths() {
//   const res = await fetch('https://reqres.in/api/users')
//   const posts = await res.json()
//   console.log('posts', posts.data)
//   const paths = posts.data.map((post) => ({
//     params: { id: post.id },
//   }))
//   return { paths, fallback: false }
// }

export async function getServerSideProps() {
  // 调用外部 API 获取博文列表
  const res = await fetch('https://reqres.in/api/users')
  const posts = await res.json()
  // 通过返回 { props: { posts } } 对象，Blog 组件
  // 在构建时将接收到 `posts` 参数
  return {
    props: {
      posts,
    },
  }
}

export default Home;
